from fastapi import APIRouter, Query
from app.schemas.products import Product, ProductsResponse

router = APIRouter(prefix="/products", tags=["products"])


mock_products = [
    {
        "id": 1,
        "title": "ナチュラルウッドボウル",
        "description": "天然素材の温かみあるボウル",
        "price": 1200,
        "rating": 4.5,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img1.jpg",
    },
    {
        "id": 2,
        "title": "リネンコースター",
        "description": "吸水性の高いリネン素材",
        "price": 800,
        "rating": 4.2,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img2.jpg",
    },
    {
        "id": 3,
        "title": "竹製カトラリーセット",
        "description": "軽くて丈夫な竹のフォーク・スプーン・ナイフ",
        "price": 1980,
        "rating": 4.6,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img3.jpg",
    },
    {
        "id": 4,
        "title": "オーガニックコットンエプロン",
        "description": "肌触りの良い未漂白コットン",
        "price": 4500,
        "rating": 4.4,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img4.jpg",
    },
    {
        "id": 5,
        "title": "セラミックマグカップ",
        "description": "手作り風のマット釉薬仕上げ",
        "price": 2200,
        "rating": 4.7,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img5.jpg",
    },
    {
        "id": 6,
        "title": "ビーワックスラップ（3枚組）",
        "description": "食品保存に使える天然蜜蝋ラップ",
        "price": 2800,
        "rating": 4.3,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img6.jpg",
    },
    {
        "id": 7,
        "title": "オリーブウッドまな板",
        "description": "オリーブの木の美しい木目",
        "price": 6800,
        "rating": 4.8,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img7.jpg",
    },
    {
        "id": 8,
        "title": "ガラス保存瓶セット",
        "description": "密閉性の高いストッカー用ボトル",
        "price": 3200,
        "rating": 4.1,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img8.jpg",
    },
    {
        "id": 9,
        "title": "ヘンプティータオル",
        "description": "速乾性に優れたヘンプ混紡",
        "price": 1500,
        "rating": 4.5,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img9.jpg",
    },
    {
        "id": 10,
        "title": "キャストアイアンスキレット",
        "description": "蓄熱性の高い鋳鉄フライパン",
        "price": 8900,
        "rating": 4.9,
        "brand": "Natulalis",
        "category": "kitchen",
        "thumbnail": "https://example.com/img10.jpg",
    },
    {
        "id": 11,
        "title": "ラベンダー入浴剤",
        "description": "天然ラベンダーの香りでリラックス",
        "price": 1100,
        "rating": 4.4,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img11.jpg",
    },
    {
        "id": 12,
        "title": "オーガニックボディソープ",
        "description": "植物由来の洗浄成分のみ使用",
        "price": 1980,
        "rating": 4.6,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img12.jpg",
    },
    {
        "id": 13,
        "title": "竹歯ブラシ（ソフト）",
        "description": "生分解性ハンドルと植物毛",
        "price": 350,
        "rating": 4.2,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img13.jpg",
    },
    {
        "id": 14,
        "title": "シアバターハンドクリーム",
        "description": "無香料の高保湿クリーム",
        "price": 1650,
        "rating": 4.7,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img14.jpg",
    },
    {
        "id": 15,
        "title": "リネンバスマット",
        "description": "足元がさらりとした天然素材マット",
        "price": 4200,
        "rating": 4.3,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img15.jpg",
    },
    {
        "id": 16,
        "title": "木製ソープディッシュ",
        "description": "水切れの良いスロット設計",
        "price": 980,
        "rating": 4.0,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img16.jpg",
    },
    {
        "id": 17,
        "title": "オーガニックフェイスタオル",
        "description": "ふんわり仕上げのコットン100%",
        "price": 2400,
        "rating": 4.5,
        "brand": "Natulalis",
        "category": "bath",
        "thumbnail": "https://example.com/img17.jpg",
    },
    {
        "id": 18,
        "title": "アロマディフューザー（柑橘）",
        "description": "天然精油ブレンドのリードディフューザー",
        "price": 3600,
        "rating": 4.4,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img18.jpg",
    },
    {
        "id": 19,
        "title": "リサイクルウールブランケット",
        "description": "リサイクル繊維のあったかひざ掛け",
        "price": 7800,
        "rating": 4.6,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img19.jpg",
    },
    {
        "id": 20,
        "title": "手編みジュートバスケット",
        "description": "収納や観葉植物カバーに",
        "price": 2900,
        "rating": 4.2,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img20.jpg",
    },
    {
        "id": 21,
        "title": "ソイキャンドル（無香料）",
        "description": "大豆ワックスのクリーンな炎",
        "price": 2200,
        "rating": 4.5,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img21.jpg",
    },
    {
        "id": 22,
        "title": "リネンクッションカバー",
        "description": "洗濯に強いナチュラルリネン",
        "price": 3200,
        "rating": 4.3,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img22.jpg",
    },
    {
        "id": 23,
        "title": "コルクコースター（6枚）",
        "description": "軽量で水に強いコルク材",
        "price": 1200,
        "rating": 4.1,
        "brand": "Natulalis",
        "category": "living",
        "thumbnail": "https://example.com/img23.jpg",
    },
    {
        "id": 24,
        "title": "オーガニックティーバッグ詰め合わせ",
        "description": "ハーブ・紅茶・アールグレイのセット",
        "price": 2600,
        "rating": 4.8,
        "brand": "Natulalis",
        "category": "food",
        "thumbnail": "https://example.com/img24.jpg",
    },
    {
        "id": 25,
        "title": "生はちみつ（百花）",
        "description": "非加熱の国産百花蜜",
        "price": 3400,
        "rating": 4.9,
        "brand": "Natulalis",
        "category": "food",
        "thumbnail": "https://example.com/img25.jpg",
    },
    {
        "id": 26,
        "title": "グラノーラ（ナッツ＆シード）",
        "description": "低糖質志向の朝食シリアル",
        "price": 1800,
        "rating": 4.4,
        "brand": "Natulalis",
        "category": "food",
        "thumbnail": "https://example.com/img26.jpg",
    },
    {
        "id": 27,
        "title": "コールドブリューコーヒー豆",
        "description": "水出し向けの中深煎りブレンド",
        "price": 2100,
        "rating": 4.5,
        "brand": "Natulalis",
        "category": "food",
        "thumbnail": "https://example.com/img27.jpg",
    },
    {
        "id": 28,
        "title": "キャンバストートバッグ",
        "description": "厚手コットンのエコバッグ",
        "price": 2800,
        "rating": 4.3,
        "brand": "Natulalis",
        "category": "outdoor",
        "thumbnail": "https://example.com/img28.jpg",
    },
    {
        "id": 29,
        "title": "ステンレス水筒（500ml）",
        "description": "真空断熱で保温保冷",
        "price": 4500,
        "rating": 4.7,
        "brand": "Natulalis",
        "category": "outdoor",
        "thumbnail": "https://example.com/img29.jpg",
    },
    {
        "id": 30,
        "title": "木製フードコンテナ",
        "description": "ランチタイムに使える二段弁当箱",
        "price": 5200,
        "rating": 4.2,
        "brand": "Natulalis",
        "category": "outdoor",
        "thumbnail": "https://example.com/img30.jpg",
    },
]


@router.get("/", response_model=ProductsResponse)
def get_products(word: str = Query("", description="検索ワード"), limit: int = Query(6, description="取得件数")):
    filtered = [
        p for p in mock_products
        if word.lower() in p["title"].lower()
    ]

    return {
        "products": filtered,
        "total": len(filtered),
        "skip": 0,
        "limit": 10,
    }